import java.util.HashMap;
import java.util.Map;

// TRADUCE el nombre del pais de Español a Ingles. IMPORTANTE lo devuelve en lower case
public class PaisTraduccion {
	private Map<String, String> traduccion;

	public PaisTraduccion() {
		this.traduccion = new HashMap<String, String>();
		traduccion.put("antigua y barbuda", "antigua and barbuda");
		traduccion.put("bután", "bhutan");
		traduccion.put("italia", "italy");
		traduccion.put("tuvalu", "tuvalu");
		traduccion.put("anguila", "anguilla");
		traduccion.put("australia", "australia");
		traduccion.put("belice", "belize");
		traduccion.put("vanuatu", "vanuatu");
		traduccion.put("bielorrusia", "belarus");
		traduccion.put("mauricio", "mauritius");
		traduccion.put("laos", "laos");
		traduccion.put("senegal", "senegal");
		traduccion.put("turquía", "turkey");
		traduccion.put("bolivia", "bolivia");
		traduccion.put("sri lanka", "sri lanka");
		traduccion.put("isla norfolk", "norfolk island");
		traduccion.put("china", "china");
		traduccion.put("caribe neerlandés", "caribbean netherlands");
		traduccion.put("guernsey", "guernsey");
		traduccion.put("sudán", "sudan");
		traduccion.put("mayotte", "mayotte");
		traduccion.put("san bartolomé", "saint barthélemy");
		traduccion.put("ciudad del vaticano", "vatican city");
		traduccion.put("islas turcas y caicos", "turks and caicos islands");
		traduccion.put("curazao", "curaçao");
		traduccion.put("botsuana", "botswana");
		traduccion.put("benín", "benin");
		traduccion.put("lituania", "lithuania");
		traduccion.put("montserrat", "montserrat");
		traduccion.put("islas vírgenes británicas", "british virgin islands");
		traduccion.put("burundi", "burundi");
		traduccion.put("islas ultramarinas de ee.uu.", "united states minor outlying islands");
		traduccion.put("irlanda", "ireland");
		traduccion.put("islas salomón", "solomon islands");
		traduccion.put("bermudas", "bermuda");
		traduccion.put("finlandia", "finland");
		traduccion.put("perú", "peru");
		traduccion.put("bangladés", "bangladesh");
		traduccion.put("dinamarca", "denmark");
		traduccion.put("san vicente y las granadinas", "saint vincent and the grenadines");
		traduccion.put("república dominicana", "dominican republic");
		traduccion.put("moldavia", "moldova");
		traduccion.put("bulgaria", "bulgaria");
		traduccion.put("costa rica", "costa rica");
		traduccion.put("namibia", "namibia");
		traduccion.put("svalbard y jan mayen", "svalbard and jan mayen");
		traduccion.put("luxemburgo", "luxembourg");
		traduccion.put("rusia", "russia");
		traduccion.put("emiratos árabes unidos", "united arab emirates");
		traduccion.put("sint maarten", "sint maarten");
		traduccion.put("bahamas", "bahamas");
		traduccion.put("japón", "japan");
		traduccion.put("nigeria", "nigeria");
		traduccion.put("ghana", "ghana");
		traduccion.put("sierra leona", "sierra leone");
		traduccion.put("san pedro y miquelón", "saint pierre and miquelon");
		traduccion.put("albania", "albania");
		traduccion.put("tokelau", "tokelau");
		traduccion.put("santa elena, ascensión y tristán de acuña", "saint helena, ascension and tristan da cunha");
		traduccion.put("tonga", "tonga");
		traduccion.put("turkmenistán", "turkmenistan");
		traduccion.put("yibuti", "djibouti");
		traduccion.put("república centroafricana", "central african republic");
		traduccion.put("líbano", "lebanon");
		traduccion.put("letonia", "latvia");
		traduccion.put("islas cocos", "cocos (keeling) islands");
		traduccion.put("gambia", "gambia");
		traduccion.put("honduras", "honduras");
		traduccion.put("niue", "niue");
		traduccion.put("mauritania", "mauritania");
		traduccion.put("kosovo", "kosovo");
		traduccion.put("wallis y futuna", "wallis and futuna");
		traduccion.put("georgia del sur", "south georgia");
		traduccion.put("polinesia francesa", "french polynesia");
		traduccion.put("togo", "togo");
		traduccion.put("bélgica", "belgium");
		traduccion.put("zambia", "zambia");
		traduccion.put("islas caimán", "cayman islands");
		traduccion.put("islas pitcairn", "pitcairn islands");
		traduccion.put("islas cook", "cook islands");
		traduccion.put("madagascar", "madagascar");
		traduccion.put("montenegro", "montenegro");
		traduccion.put("corea del sur", "south korea");
		traduccion.put("etiopía", "ethiopia");
		traduccion.put("mongolia", "mongolia");
		traduccion.put("eslovaquia", "slovakia");
		traduccion.put("cuba", "cuba");
		traduccion.put("antártida", "antarctica");
		traduccion.put("guatemala", "guatemala");
		traduccion.put("guayana francesa", "french guiana");
		traduccion.put("noruega", "norway");
		traduccion.put("granada", "grenada");
		traduccion.put("reunión", "réunion");
		traduccion.put("chile", "chile");
		traduccion.put("colombia", "colombia");
		traduccion.put("arabia saudita", "saudi arabia");
		traduccion.put("israel", "israel");
		traduccion.put("alemania", "germany");
		traduccion.put("nueva zelanda", "new zealand");
		traduccion.put("groenlandia", "greenland");
		traduccion.put("kirguistán", "kyrgyzstan");
		traduccion.put("el salvador", "el salvador");
		traduccion.put("islas feroe", "faroe islands");
		traduccion.put("palaos", "palau");
		traduccion.put("malta", "malta");
		traduccion.put("siria", "syria");
		traduccion.put("timor oriental", "timor-leste");
		traduccion.put("croacia", "croatia");
		traduccion.put("papúa nueva guinea", "papua new guinea");
		traduccion.put("países bajos", "netherlands");
		traduccion.put("liberia", "liberia");
		traduccion.put("somalia", "somalia");
		traduccion.put("venezuela", "venezuela");
		traduccion.put("haití", "haiti");
		traduccion.put("argelia", "algeria");
		traduccion.put("islas marianas del norte", "northern mariana islands");
		traduccion.put("saint-martin", "saint martin");
		traduccion.put("islas heard y mcdonald", "heard island and mcdonald islands");
		traduccion.put("aruba", "aruba");
		traduccion.put("egipto", "egypt");
		traduccion.put("malaui", "malawi");
		traduccion.put("guinea ecuatorial", "equatorial guinea");
		traduccion.put("islas vírgenes de los ee.uu.", "united states virgin islands");
		traduccion.put("ecuador", "ecuador");
		traduccion.put("uzbekistán", "uzbekistan");
		traduccion.put("gabón", "gabon");
		traduccion.put("sudán del sur", "south sudan");
		traduccion.put("irán", "iran");
		traduccion.put("kazajistán", "kazakhstan");
		traduccion.put("nicaragua", "nicaragua");
		traduccion.put("islandia", "iceland");
		traduccion.put("eslovenia", "slovenia");
		traduccion.put("guadalupe", "guadeloupe");
		traduccion.put("camerún", "cameroon");
		traduccion.put("argentina", "argentina");
		traduccion.put("azerbaiyán", "azerbaijan");
		traduccion.put("uganda", "uganda");
		traduccion.put("níger", "niger");
		traduccion.put("isla de navidad", "christmas island");
		traduccion.put("birmania", "myanmar");
		traduccion.put("polonia", "poland");
		traduccion.put("jordania", "jordan");
		traduccion.put("hong kong", "hong kong");
		traduccion.put("república democrática del congo", "dr congo");
		traduccion.put("eritrea", "eritrea");
		traduccion.put("kiribati", "kiribati");
		traduccion.put("islas marshall", "marshall islands");
		traduccion.put("burkina faso", "burkina faso");
		traduccion.put("zimbabue", "zimbabwe");
		traduccion.put("kenia", "kenya");
		traduccion.put("comoras", "comoros");
		traduccion.put("gibraltar", "gibraltar");
		traduccion.put("brunéi", "brunei");
		traduccion.put("suecia", "sweden");
		traduccion.put("lesoto", "lesotho");
		traduccion.put("isla de man", "isle of man");
		traduccion.put("micronesia", "micronesia");
		traduccion.put("tanzania", "tanzania");
		traduccion.put("cabo verde", "cape verde");
		traduccion.put("afganistán", "afghanistan");
		traduccion.put("andorra", "andorra");
		traduccion.put("grecia", "greece");
		traduccion.put("vietnam", "vietnam");
		traduccion.put("tierras australes francesas", "french southern and antarctic lands");
		traduccion.put("irak", "iraq");
		traduccion.put("libia", "libya");
		traduccion.put("portugal", "portugal");
		traduccion.put("pakistán", "pakistan");
		traduccion.put("maldivas", "maldives");
		traduccion.put("marruecos", "morocco");
		traduccion.put("bosnia y herzegovina", "bosnia and herzegovina");
		traduccion.put("samoa", "samoa");
		traduccion.put("palestina", "palestine");
		traduccion.put("omán", "oman");
		traduccion.put("baréin", "bahrain");
		traduccion.put("estados unidos", "united states");
		traduccion.put("puerto rico", "puerto rico");
		traduccion.put("territorio británico del océano índico", "british indian ocean territory");
		traduccion.put("jersey", "jersey");
		traduccion.put("macedonia del norte", "north macedonia");
		traduccion.put("túnez", "tunisia");
		traduccion.put("trinidad y tobago", "trinidad and tobago");
		traduccion.put("estonia", "estonia");
		traduccion.put("singapur", "singapore");
		traduccion.put("panamá", "panama");
		traduccion.put("suiza", "switzerland");
		traduccion.put("uruguay", "uruguay");
		traduccion.put("tayikistán", "tajikistan");
		traduccion.put("taiwán", "taiwan");
		traduccion.put("sudáfrica", "south africa");
		traduccion.put("liechtenstein", "liechtenstein");
		traduccion.put("brasil", "brazil");
		traduccion.put("armenia", "armenia");
		traduccion.put("georgia", "georgia");
		traduccion.put("islas åland", "åland islands");
		traduccion.put("catar", "qatar");
		traduccion.put("dominica", "dominica");
		traduccion.put("ucrania", "ukraine");
		traduccion.put("guinea", "guinea");
		traduccion.put("macao", "macao");
		traduccion.put("sahara occidental", "western sahara");
		traduccion.put("chequia", "czechia");
		traduccion.put("austria", "austria");
		traduccion.put("san cristóbal y nieves", "saint kitts and nevis");
		traduccion.put("santa lucía", "saint lucia");
		traduccion.put("yemen", "yemen");
		traduccion.put("ruanda", "rwanda");
		traduccion.put("mónaco", "monaco");
		traduccion.put("santo tomé y príncipe", "são tomé and príncipe");
		traduccion.put("república del congo", "republic of the congo");
		traduccion.put("paraguay", "paraguay");
		traduccion.put("isla bouvet", "bouvet island");
		traduccion.put("mozambique", "mozambique");
		traduccion.put("francia", "france");
		traduccion.put("esuatini", "eswatini");
		traduccion.put("barbados", "barbados");
		traduccion.put("españa", "spain");
		traduccion.put("tailandia", "thailand");
		traduccion.put("guinea-bisáu", "guinea-bissau");
		traduccion.put("angola", "angola");
		traduccion.put("india", "india");
		traduccion.put("martinica", "martinique");
		traduccion.put("nueva caledonia", "new caledonia");
		traduccion.put("seychelles", "seychelles");
		traduccion.put("islas malvinas", "falkland islands");
		traduccion.put("reino unido", "united kingdom");
		traduccion.put("fiyi", "fiji");
		traduccion.put("san marino", "san marino");
		traduccion.put("malí", "mali");
		traduccion.put("canadá", "canada");
		traduccion.put("jamaica", "jamaica");
		traduccion.put("nauru", "nauru");
		traduccion.put("indonesia", "indonesia");
		traduccion.put("guam", "guam");
		traduccion.put("costa de marfil", "ivory coast");
		traduccion.put("kuwait", "kuwait");
		traduccion.put("filipinas", "philippines");
		traduccion.put("guyana", "guyana");
		traduccion.put("hungría", "hungary");
		traduccion.put("méxico", "mexico");
		traduccion.put("corea del norte", "north korea");
		traduccion.put("rumania", "romania");
		traduccion.put("surinam", "suriname");
		traduccion.put("samoa americana", "american samoa");
		traduccion.put("nepal", "nepal");
		traduccion.put("chad", "chad");
		traduccion.put("serbia", "serbia");
		traduccion.put("camboya", "cambodia");
		traduccion.put("malasia", "malaysia");
		traduccion.put("chipre", "cyprus");

	}
	/**	
	 * TRADUCE el nombre del pais de Español a Ingles. IMPORTANTE lo devuelve en lower case
	 *
	 * @return traduccionIngles
	 */
	public String traducirPais(String pais) {
		// A lower case
		String paisTraducir = pais.toLowerCase();
		
		// Busca si esta en el map
		if(traduccion.containsKey(paisTraducir)) {
			System.out.println("Desde traducir pais, devuelvo: " + traduccion.get(paisTraducir));
			// Devuelve el pais traducido
			return traduccion.get(paisTraducir);
		}else {
			// Si no esta devuelve null
			return null;
		}
	}
}
